"""
PC Monitor - 자녀 PC 사용 모니터링 도구
메인 실행 스크립트

기능:
- 일일 데이터 수집 및 저장
- 날짜별 HTML 리포트 생성
- 대시보드에서 날짜별 조회
"""

import os
import sys
import webbrowser
from datetime import datetime, timedelta

# src 폴더를 경로에 추가
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from browser_history import get_all_browser_history, get_domain_statistics
from app_usage import get_all_app_usage, filter_common_programs
from pc_time import get_pc_usage_summary
from recent_files import get_recent_files_summary
from roblox_games import get_roblox_summary
from report_generator import generate_html_report, generate_dashboard_html
from data_storage import save_daily_data, get_available_dates


def print_banner():
    """배너 출력"""
    print()
    print("=" * 60)
    print("   PC Monitor - 자녀 PC 사용 모니터링 도구")
    print("   Generated by Claude Code")
    print("=" * 60)
    print()


def collect_all_data(days: int = 1, use_sample_roblox: bool = True, filter_date: str = None) -> dict:
    """모든 데이터 수집

    Args:
        days: 최근 며칠간의 데이터를 수집할지
        use_sample_roblox: 로블록스 데이터 없을 때 샘플 사용 여부
        filter_date: 특정 날짜만 필터링 (YYYY-MM-DD)

    Returns:
        수집된 모든 데이터
    """
    if filter_date is None:
        filter_date = datetime.now().strftime('%Y-%m-%d')

    print(f"[*] {filter_date} 데이터를 수집합니다...")
    print()

    # 1. 브라우저 방문 기록 (오늘 날짜만)
    print("[1/5] 브라우저 방문 기록 수집 중...")
    browser_history = get_all_browser_history(days=days, filter_date=filter_date)
    domain_stats = get_domain_statistics(browser_history)

    # 2. 프로그램 실행 기록 (오늘 날짜만)
    print("[2/5] 프로그램 실행 기록 수집 중...")
    app_usage = get_all_app_usage(filter_date=filter_date)
    if app_usage.get('prefetch'):
        app_usage['prefetch'] = filter_common_programs(app_usage['prefetch'])

    # 3. PC 사용 시간 (해당 날짜만)
    print("[3/5] PC 사용 시간 수집 중...")
    pc_time = get_pc_usage_summary(filter_date=filter_date)

    # 4. 최근 파일 접근 (오늘 날짜만)
    print("[4/5] 최근 파일 접근 기록 수집 중...")
    recent_files = get_recent_files_summary(filter_date=filter_date)

    # 5. 로블록스 게임 기록
    print("[5/5] 로블록스 게임 기록 수집 중...")
    roblox = get_roblox_summary(browser_history, use_sample=use_sample_roblox)

    print()
    print("[+] 데이터 수집 완료!")
    print()

    return {
        'browser_history': browser_history,
        'domain_stats': domain_stats,
        'app_usage': app_usage,
        'pc_time': pc_time,
        'recent_files': recent_files,
        'roblox': roblox
    }


def main():
    """메인 함수"""
    print_banner()

    # 출력 폴더 확인
    output_dir = os.path.join(os.path.dirname(__file__), 'output')
    os.makedirs(output_dir, exist_ok=True)

    # 최근 7일치 데이터 수집
    collect_days = 7
    today = datetime.now()
    dates_with_data = []

    print(f"[*] 최근 {collect_days}일간의 데이터를 수집합니다...")
    print()

    for i in range(collect_days):
        target_date = (today - timedelta(days=i)).strftime('%Y-%m-%d')

        print("-" * 60)
        print(f"[날짜 {i+1}/{collect_days}] {target_date}")
        print("-" * 60)

        # 데이터 수집 (해당 날짜만)
        # 오늘만 샘플 로블록스 데이터 사용
        use_sample = (i == 0)
        data = collect_all_data(days=collect_days, use_sample_roblox=use_sample, filter_date=target_date)

        # 데이터가 있는지 확인 (브라우저 기록, 프로그램 실행, 파일 접근 중 하나라도 있으면)
        has_data = (
            len(data.get('browser_history', [])) > 0 or
            len(data.get('app_usage', {}).get('prefetch', [])) > 0 or
            len(data.get('recent_files', {}).get('files', [])) > 0
        )

        if has_data:
            dates_with_data.append(target_date)

            # 1. 일일 데이터를 JSON으로 저장
            print(f"[*] {target_date} 데이터 저장 중...")
            save_daily_data(data, target_date)

            # 2. 해당 날짜의 HTML 리포트 생성
            print(f"[*] {target_date} HTML 리포트 생성 중...")
            daily_report_path = os.path.join(output_dir, f'daily_{target_date}.html')
            generate_html_report(data, daily_report_path)
        else:
            print(f"[!] {target_date}: 데이터 없음 (건너뜀)")

        print()

    # 3. 대시보드 HTML 생성 (날짜 선택 가능)
    print("[*] 대시보드 생성 중...")
    available_dates = get_available_dates()
    dashboard_path = os.path.join(output_dir, 'dashboard.html')
    generate_dashboard_html(available_dates, dashboard_path)

    print()
    print("=" * 60)
    print(f"   완료!")
    print(f"   - 대시보드: {dashboard_path}")
    print(f"   - 데이터가 있는 날짜: {len(dates_with_data)}일")
    if dates_with_data:
        print(f"   - 날짜 목록: {', '.join(dates_with_data)}")
    print("=" * 60)
    print()

    # 대시보드를 브라우저에서 열기
    try:
        print("[*] 대시보드를 브라우저에서 엽니다...")
        webbrowser.open(f'file://{os.path.abspath(dashboard_path)}')
    except Exception as e:
        print(f"[!] 브라우저 열기 실패: {e}")
        print(f"    직접 파일을 열어주세요: {dashboard_path}")


if __name__ == '__main__':
    main()
